### PR TITLE
Check if file exists before opening

### LINKED ISSUE #2: FileNotFoundError on OSX
```py
  File "/Users/uuu/Library/Caches/pypoetry/virtualenvs/django-backend-8_JPUAxs-py3.6/lib/python3.6/site-packages/docker_check/checker.py", line 20, in is_inside_container
    if has_docker_in_proc_1_cgroup():
  File "/Users/uuu/Library/Caches/pypoetry/virtualenvs/django-backend-8_JPUAxs-py3.6/lib/python3.6/site-packages/docker_check/checker.py", line 10, in has_docker_in_proc_1_cgroup
    with open('/proc/1/cgroup', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/cgroup'
```

### PR DESCRIPTION
**Pull request by jayvdb**
Avoids an exception on non-Linux OS.

Fixes https://github.com/night-crawler/docker-check/issues/2

### CODE REVIEW

**Review by night-crawler — APPROVED** [review]

**Comment by jayvdb** [comment]
This one warrants a new release?

**Comment by night-crawler** [comment]
Yep, but there's a minor problem here. I have to remember how to upload python stuff on PyPI =)

I'll do it in a while.

**Comment by jayvdb** [comment]
*chuckle*  No worries ; I'm installing from master in my project.

**Comment by jayvdb** [comment]
ping @night-crawler . I would rather be installing from PyPI than `git+` which is slower.

**Pull request merged**
